anthR.Web/Models/Core/StaffOnTask.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace anthR.Web.Models.Core
{
    
    public class StaffOnTask
    {

        [Key]
        [Column(Order = 0)]
        public int StaffId { get; set; }
        public virtual Staff Staff { get; set; }

        [Key]
        [Column(Order = 1)]
        public int AnthRTaskId { get; set; }
        public virtual arTask.AnthRTask AnthRTask { get; set; }

    }

}

anthR.Web/Controllers/API/StaffOnTasksController.cs
using anthR.Web.Models.Core;
using anthR.Web.Models.Email;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace anthR.Web.Controllers.API
{
    public class StaffOnTasksController : ApiController
    {
                
        private anthRContext _db = new anthRContext();
                        
        public HttpResponseMessage Post(StaffToAdd staffToAdd)
        {

            Notification notificationService = null;
            // for each staff id in the staffid array, add to the db.
            foreach (var staffId in staffToAdd.StaffId)
            {
                // add staff
                _db.StaffOnTask.Add(new StaffOnTask() { StaffId = staffId, AnthRTaskId = staffToAdd.AnthRTaskId });

                // send off email to the staff member informing them of the new task
                notificationService = new Notification();
                notificationService.SendTaskEmail(staffToAdd.AnthRTaskId, staffId);

            }
            _db.SaveChanges();

            return new HttpResponseMessage(HttpStatusCode.OK);

        }

        protected override void Dispose(bool disposing)
        {

            if (_db != null)
            {
                _db.Dispose();
                _db = null;
            }

            base.Dispose(disposing);
        }
        
    }

}

anthR.Web/Controllers/StaffOnTasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using anthR.Web.Models.Core;
using System.Net.Mail;

namespace anthR.Web.Controllers
{
    public class StaffOnTasksController : Controller
    {
        private anthRContext db = new anthRContext();

        // GET: StaffOnTasks
        public async Task<ActionResult> Index()
        {             
            var staffOnTask = db.StaffOnTask.Include(s => s.AnthRTask).Include(s => s.Staff);
            return View(await staffOnTask.ToListAsync());
        }

        // GET: StaffOnTasks/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StaffOnTask staffOnTask = await db.StaffOnTask.FindAsync(id);
            if (staffOnTask == null)
            {
                return HttpNotFound();
            }
            return View(staffOnTask);
        }

        // GET: StaffOnTasks/Create
        public ActionResult Create(int id, int? taskId)
        {

            // load staff only on the projectid passed in
            var staff = db.Staff.Where(s => s.StaffOnProjects.Where(p => p.ProjectId.Equals(id)).Any());

            ViewBag.AnthRTask = new SelectList(db.AnthRTask, "Id", "Name", (taskId.HasValue ? taskId.Value : 0));
            ViewBag.StaffId = new SelectList(staff.ToList(), "Id", "Name");
            ViewBag.ProjectId = id;

            return View();

        }

        // POST: StaffOnTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(int id, [Bind(Include = "StaffId,AnthRTaskId")] StaffOnTask staffOnTask)
        {
            if (ModelState.IsValid)
            {
                db.StaffOnTask.Add(staffOnTask);
                await db.SaveChangesAsync();
                                
                // send off email to the staff member informing them of the new task
                this.SendTaskEmail(staffOnTask.AnthRTaskId, staffOnTask.StaffId);

                //redirect to task index
                return RedirectToAction("Index", "Tasks", new { id = id });
            }

            var staff = db.Staff.Where(s => s.StaffOnProjects.Where(p => p.ProjectId.Equals(id)).Any());

            ViewBag.AnthRTaskId = new SelectList(db.AnthRTask, "Id", "Name", staffOnTask.AnthRTaskId);
            ViewBag.StaffId = new SelectList(staff.ToList(), "Id", "Name", staffOnTask.StaffId);
            return View(staffOnTask);
        }

        // GET: StaffOnTasks/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StaffOnTask staffOnTask = await db.StaffOnTask.FindAsync(id);
            if (staffOnTask == null)
            {
                return HttpNotFound();
            }
            ViewBag.AnthRTaskId = new SelectList(db.AnthRTask, "Id", "Name", staffOnTask.AnthRTaskId);
            ViewBag.StaffId = new SelectList(db.Staff, "Id", "Name", staffOnTask.StaffId);
            return View(staffOnTask);
        }

        // POST: StaffOnTasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "StaffId,AnthRTaskId")] StaffOnTask staffOnTask)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staffOnTask).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.AnthRTaskId = new SelectList(db.AnthRTask, "Id", "Name", staffOnTask.AnthRTaskId);
            ViewBag.StaffId = new SelectList(db.Staff, "Id", "Name", staffOnTask.StaffId);
            return View(staffOnTask);
        }

        // GET: StaffOnTasks/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StaffOnTask staffOnTask = await db.StaffOnTask.FindAsync(id);
            if (staffOnTask == null)
            {
                return HttpNotFound();
            }
            return View(staffOnTask);
        }

        // POST: StaffOnTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            StaffOnTask staffOnTask = await db.StaffOnTask.FindAsync(id);
            db.StaffOnTask.Remove(staffOnTask);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private void SendTaskEmail(int taskId, int staffId)
        {
            
            // load up the task
            var anthRTask = db.AnthRTask.Where(t => t.Id.Equals(taskId)).FirstOrDefault();
            var body = anthR.Utils.IO.Razor.RenderViewToString(this, "EmailTaskInformation", anthRTask);

            // get the staff member details
            var staffMember = db.Staff.Where(s => s.Id.Equals(staffId)).FirstOrDefault();

            var staffEmail = staffMember.Email;
            
            Task.Factory.StartNew(() =>
            {
                
                MailMessage mailMessage = null;
                SmtpClient smtpClient = null;

                try
                {
                
                    mailMessage = new MailMessage();
                    mailMessage.To.Add(staffEmail);                
                    mailMessage.From = new MailAddress("online@kingfisher-systems.co.uk");
                    mailMessage.IsBodyHtml = true;
                    mailMessage.Body = body;
                    mailMessage.Subject = string.Format("anthR Task Assignment");

                    smtpClient = new SmtpClient();
                    smtpClient.Send(mailMessage);

                }
                catch (SmtpException smtpEx)
                {
                    throw smtpEx;
                }
                catch (Exception ex)
                {
                    throw ex;
                }

            }).ConfigureAwait(false);
            
        }

        public ActionResult EmailTaskInformation()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

anthR.Web/Views/StaffOnTasks/Create.cshtml
@model anthR.Web.Models.Core.StaffOnTask

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_TodoLayout.cshtml";
}

@section head{
    <link href="~/Content/AppCss/bootstrap/bootstrap-multiselect.css" rel="stylesheet" />
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "StaffOnTasks", FormMethod.Post, new { id = "add-form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StaffOnTask</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StaffId, "StaffId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StaffId", null, htmlAttributes: new { @class = "form-control", multiple = "multiple" })
                @Html.ValidationMessageFor(model => model.StaffId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnthRTaskId, "AnthRTaskId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AnthRTaskId", (SelectList)ViewBag.AnthRTask, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AnthRTaskId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Add Staff Member(s)</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts{

    @*http://davidstutz.github.io/bootstrap-multiselect/*@
    <script src="~/Scripts/bootstrap/bootstrap-multiselect.js"></script>
    <script>
        $(function () {

            // setup the multiselect
            $('#StaffId').multiselect();

            // handle the form submit through the API
            var $form = $('#add-form');
            $form.submit(function (e) {
                e.preventDefault();

                // disable the button
                $form.find('input[type="submit"]').attr('disabled', 'disabled');

                // post to api
                $.post("/api/staffontasks", $form.serialize(), function (data) {

                }).done(function (data, textStatus, xhr) {

                    // check the status code
                    switch (xhr.status) {
                        case 200:
                            // everything is fine and dandy!
                            // change window to the task view
                            var projectId = @ViewBag.ProjectId;
                            //window.location = '/projects/index';
                            window.location = '/tasks/index/' + projectId;
                    }

                    //console.log('data', data);
                    //console.log('textStatus', textStatus);
                    //console.log('xhr', xhr);

                });

                return false;

            });

        });
    </script>
}

anthR.Web/Views/StaffOnTasks/Delete.cshtml
@model anthR.Web.Models.Core.StaffOnTask

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_TodoLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StaffOnTask</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AnthRTask.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnthRTask.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Staff.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Staff.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

anthR.Web/Views/StaffOnTasks/Details.cshtml
@model anthR.Web.Models.Core.StaffOnTask

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_TodoLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>StaffOnTask</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AnthRTask.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnthRTask.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Staff.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Staff.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

anthR.Web/Views/StaffOnTasks/Edit.cshtml
@model anthR.Web.Models.Core.StaffOnTask

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_TodoLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StaffOnTask</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StaffId)

        @Html.HiddenFor(model => model.AnthRTaskId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

anthR.Web/Views/StaffOnTasks/EmailTaskInformation.cshtml
@model anthR.Web.Models.arTask.AnthRTask

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Model.Project.Name - @Model.Name</title>
</head>
<body>

    <p>
        @Model.Project.MasterSite.Name - @Model.Project.Name - @Model.Name
    </p>

    <p>You have been assigned to a Task. Please visit <a href="@string.Format("http://tim-hp:82/Tasks/Details/{0}", Model.Id)">anthR.Task</a> to view the details.</p>

</body>
</html>

anthR.Web/Views/StaffOnTasks/Index.cshtml
@model IEnumerable<anthR.Web.Models.Core.StaffOnTask>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TodoLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AnthRTask.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Staff.Name)
        </th>
        <th class="text-right">Options</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AnthRTask.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Staff.Name)
        </td>
        <td class="text-right">
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-xs btn-primary", role = "button" })
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-xs btn-primary", role = "button" })
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-xs btn-primary", role = "button" })
        </td>
    </tr>
}

</table>