anthR.Web/Models/Core/StaffOnProjects.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace anthR.Web.Models.Core
{
    public class StaffOnProjects
    {
        [Key]
        [Column(Order = 0)]
        public int StaffId { get; set; }
        public virtual Staff Staff { get; set; }

        [Key]
        [Column(Order = 1)]
        public int ProjectId { get; set; }
        public virtual Project Project { get; set; }
    }
}

anthR.Web/Controllers/API/StaffOnProjectsController.cs
using anthR.Web.Models.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Cors;

namespace anthR.Web.Controllers.API
{
 
    [EnableCors(origins: "http://localhost:35438", headers: "*", methods: "*")]
    public class StaffOnProjectsController : ApiController
    {

        private anthRContext _db = new anthRContext();

        public string Get()
        {
            return "Hello World";
        }
                
        public HttpResponseMessage Post(StaffToAdd staffToAdd)
        {     
       
            // for each staff id in the staffid array, add to the db.
            foreach (var staffId in staffToAdd.StaffId)
            {
                // add staff
                _db.StaffOnProjects.Add(new StaffOnProjects() { StaffId = staffId, ProjectId = staffToAdd.ProjectId });
            }
            _db.SaveChanges();

            return new HttpResponseMessage(HttpStatusCode.OK);

        }

        protected override void Dispose(bool disposing)
        {

            if (_db != null)
            {
                _db.Dispose();
                _db = null;
            }

            base.Dispose(disposing);
        }

    }

    public class StaffToAdd
    {
        public int[] StaffId { get; set; }
        public int ProjectId { get; set; }
        public int AnthRTaskId { get; set; }
    }

}

anthR.Web/Controllers/StaffOnProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using anthR.Web.Models.Core;

namespace anthR.Web.Controllers
{
    public class StaffOnProjectsController : Controller
    {
        private anthRContext db = new anthRContext();

        // GET: StaffOnProjects
        public async Task<ActionResult> Index()
        {
            var staffOnProjects = db.StaffOnProjects.Include(s => s.Project).Include(s => s.Staff);
            return View(await staffOnProjects.ToListAsync());
        }

        // GET: StaffOnProjects/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StaffOnProjects staffOnProjects = await db.StaffOnProjects.FindAsync(id);
            if (staffOnProjects == null)
            {
                return HttpNotFound();
            }
            return View(staffOnProjects);
        }

        // GET: StaffOnProjects/Create
        public ActionResult Create(int? id)
        {
            ViewBag.Projects = new SelectList(db.Project, "Id", "Name", (id.HasValue ? id.Value : 0));
            ViewBag.StaffId = new SelectList(db.Staff, "Id", "Name");            
            return View();
        }

        // POST: StaffOnProjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "StaffId,ProjectId")] StaffOnProjects staffOnProjects)
        {
            if (ModelState.IsValid)
            {
                db.StaffOnProjects.Add(staffOnProjects);
                await db.SaveChangesAsync();
                //return RedirectToAction("Index");
                // redirect to project index
                return RedirectToAction("Index", "Projects");
            }

            ViewBag.ProjectId = new SelectList(db.Project, "Id", "Name", staffOnProjects.ProjectId);
            ViewBag.StaffId = new SelectList(db.Staff, "Id", "Name", staffOnProjects.StaffId);
            return View(staffOnProjects);
        }

        // GET: StaffOnProjects/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StaffOnProjects staffOnProjects = await db.StaffOnProjects.FindAsync(id);
            if (staffOnProjects == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectId = new SelectList(db.Project, "Id", "Name", staffOnProjects.ProjectId);
            ViewBag.StaffId = new SelectList(db.Staff, "Id", "Name", staffOnProjects.StaffId);
            return View(staffOnProjects);
        }

        // POST: StaffOnProjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "StaffId,ProjectId")] StaffOnProjects staffOnProjects)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staffOnProjects).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectId = new SelectList(db.Project, "Id", "Name", staffOnProjects.ProjectId);
            ViewBag.StaffId = new SelectList(db.Staff, "Id", "Name", staffOnProjects.StaffId);
            return View(staffOnProjects);
        }

        // GET: StaffOnProjects/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StaffOnProjects staffOnProjects = await db.StaffOnProjects.FindAsync(id);
            if (staffOnProjects == null)
            {
                return HttpNotFound();
            }
            return View(staffOnProjects);
        }

        // POST: StaffOnProjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            StaffOnProjects staffOnProjects = await db.StaffOnProjects.FindAsync(id);
            db.StaffOnProjects.Remove(staffOnProjects);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

anthR.Web/Views/StaffOnProjects/Create.cshtml
@model anthR.Web.Models.Core.StaffOnProjects

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_TodoLayout.cshtml";
}

@section head{
    <link href="~/Content/AppCss/bootstrap/bootstrap-multiselect.css" rel="stylesheet" />
}

<h2>Add Staff to Project</h2>

@using (Html.BeginForm("Create", "StaffOnProjects", FormMethod.Post, new { id = "add-form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StaffId, "Staff Member", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StaffId", null, htmlAttributes: new { @class = "form-control", multiple = "multiple" })
                @Html.ValidationMessageFor(model => model.StaffId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectId, "Project", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectId", (SelectList)ViewBag.Projects, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Add Staff Member(s)</button>                
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts{

    @*http://davidstutz.github.io/bootstrap-multiselect/*@
    <script src="~/Scripts/bootstrap/bootstrap-multiselect.js"></script>
    <script>
        $(function () {

            // setup the multiselect
            $('#StaffId').multiselect();

            // handle the form submit through the API
            var $form = $('#add-form');
            $form.submit(function (e) {
                e.preventDefault();

                // disable the button
                $form.find('input[type="submit"]').attr('disabled', 'disabled');

                // post to api
                $.post("/api/staffonprojects", $form.serialize(), function (data) {

                }).done(function (data, textStatus, xhr) {

                    // check the status code
                    switch (xhr.status) {
                        case 200:
                            // everything is fine and dandy!
                            // change window to the task view
                            window.location = '/projects/index';
                    }

                    //console.log('data', data);
                    //console.log('textStatus', textStatus);
                    //console.log('xhr', xhr);

                });

                return false;

            });

        });
    </script>
}

anthR.Web/Views/StaffOnProjects/Delete.cshtml
@model anthR.Web.Models.Core.StaffOnProjects

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_TodoLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StaffOnProjects</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Project.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Staff.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Staff.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

anthR.Web/Views/StaffOnProjects/Details.cshtml
@model anthR.Web.Models.Core.StaffOnProjects

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_TodoLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>StaffOnProjects</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Project.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Staff.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Staff.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

anthR.Web/Views/StaffOnProjects/Edit.cshtml
@model anthR.Web.Models.Core.StaffOnProjects

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_TodoLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StaffOnProjects</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StaffId)

        @Html.HiddenFor(model => model.ProjectId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

anthR.Web/Views/StaffOnProjects/Index.cshtml
@model IEnumerable<anthR.Web.Models.Core.StaffOnProjects>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TodoLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Project.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Staff.Name)
        </th>
        <th class="text-right">Options</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Project.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Staff.Name)
        </td>
        <td class="text-right">
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-xs btn-primary", role = "button" })
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-xs btn-primary", role = "button" })
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-xs btn-primary", role = "button" })
        </td>
    </tr>
}

</table>