anthR.Web/Models/Task/AnthRTask.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using anthR.Web.Models.Core;
using System.ComponentModel.DataAnnotations;

namespace anthR.Web.Models.Task
{
    public class AnthRTask
    {
        
        public int Id { get; set; }

        public string Username { get; set; }

        [Display(Name = "Task")]
        public string Name { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public DateTime Deadline { get; set; }
        [Display(Name = "Planned Start")]
        public DateTime PlannedStart { get; set; }
        [Display(Name = "Date Completed")]
        public DateTime? DateCompleted { get; set; }

        [Display(Name = "Requested By")]
        public string RequestedBy { get; set; }
        [Display(Name = "Agreed With")]
        public string AgreedWith { get; set; }

        public int ProjectId { get; set; }
        public virtual Project Project { get; set; }

        public virtual ICollection<StaffOnTask> StaffOnTasks { get; set; }

        public int StatusId { get; set; }
        public virtual Status Status { get; set; }

        public int Priority { get; set; }

        public virtual ICollection<Timesheet> Timesheet { get; set; }

    }
}

anthR.Web/Models/Task/Timesheet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace anthR.Web.Models.Task
{
    
    public class Timesheet
    {

        public int Id { get; set; }
        public int Hours { get; set; }
        public int Mins { get; set; }

        [Display(Name = "Hourly Rate")]
        public int HourlyRate { get; set; }

        [Display(Name = "Date Recorded")]
        public DateTime? DateRecorded { get; set; }

        public double Quoted { get; set; }

        public bool AlreadyBilled { get; set; }
        
        public int StaffId { get; set; }
        public virtual Core.Staff Staff { get; set; }

        public int AnthRTaskId { get; set; }
        public virtual AnthRTask AnthRTask { get; set; }

    }

}

anthR.Web/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using anthR.Web.Models.Core;

namespace anthR.Web.Controllers
{
    public class StaffController : Controller
    {
        private anthRContext db = new anthRContext();

        // GET: Staff
        public async Task<ActionResult> Index()
        {
            return View(await db.Staff.ToListAsync());
        }

        // GET: Staff/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = await db.Staff.FindAsync(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staff/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Staff/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Email,Username")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Staff.Add(staff);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(staff);
        }

        // GET: Staff/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = await db.Staff.FindAsync(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staff/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Email,Username")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(staff);
        }

        // GET: Staff/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = await db.Staff.FindAsync(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staff/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Staff staff = await db.Staff.FindAsync(id);
            db.Staff.Remove(staff);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
                
        public async Task<ActionResult> StaffGravatar()
        {

            var staffService = new anthR.Web.Models.Core.StaffService();
            var staffMember = await staffService.GetStaffMemberAsync(User.Identity.Name);            

            return View(staffMember);

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

anthR.Web/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using anthR.Web.Models.Core;
using anthR.Web.Models.arTask;

namespace anthR.Web.Controllers
{
    public class TasksController : Controller
    {

        //private int _completedStatusId = 4;
        private anthRContext _db = new anthRContext();

        // GET: AnthRTasks
        public async Task<ActionResult> Index(int? id, bool? completed, string all)
        {
            
            List<AnthRTask> anthRTask = null;

            if (!completed.HasValue)
            {
                anthRTask = await _db.AnthRTask.Where(t => !id.HasValue 
                    && !t.DateCompleted.HasValue 
                    && (
                            t.Username.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase) 
                            || 
                            t.StaffOnTasks.Where(st => st.Staff.Username.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase)).Any()
                            || (!string.IsNullOrEmpty(all) && all.Equals("true", StringComparison.OrdinalIgnoreCase))
                        ) 
                    || t.ProjectId.Equals(id.Value) 
                    && !t.DateCompleted.HasValue 
                    && (
                        t.Username.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase) 
                        || 
                        t.StaffOnTasks.Where(st => st.Staff.Username.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase)).Any()
                        || (!string.IsNullOrEmpty(all) && all.Equals("true", StringComparison.OrdinalIgnoreCase))
                    )
                )                
                .OrderBy(p => p.Priority)
                .ThenBy(p => p.Deadline)                
                .ThenBy(p => p.PlannedStart)                
                .Include(a => a.Project).ToListAsync();
            }
            else
            {
                anthRTask = await _db.AnthRTask.Where(t => !id.HasValue && t.DateCompleted.HasValue
                    && (
                        t.Username.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase) 
                        || 
                        t.StaffOnTasks.Where(st => st.Staff.Username.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase)).Any()
                        || (!string.IsNullOrEmpty(all) && all.Equals("true", StringComparison.OrdinalIgnoreCase))
                    )
                    || t.ProjectId.Equals(id.Value) 
                    && t.DateCompleted.HasValue
                    && (
                        t.Username.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase) 
                        || 
                        t.StaffOnTasks.Where(st => st.Staff.Username.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase)).Any()
                        || (!string.IsNullOrEmpty(all) && all.Equals("true", StringComparison.OrdinalIgnoreCase))
                    )
                )                
                .OrderBy(p => p.Priority)
                .ThenBy(p => p.Deadline)                
                .ThenBy(p => p.PlannedStart)                
                .Include(a => a.Project).ToListAsync();
            }
                
            // if we have a project id, then load project details and assign to breadcrumbextra
            if (id.HasValue)
            {
                
                Project project = null;
                if (anthRTask.Count > 0)
                {
                    project = anthRTask.FirstOrDefault().Project;
                }
                else
                {
                    project = await _db.Project.Where(p => p.Id.Equals(id.Value)).FirstOrDefaultAsync();                
                }
                                
                ViewBag.BreadcrumbExtra = string.Format("- {0} - {1}", project.MasterSite.Name, project.Name);              
                
            }
            else
            {
                ViewBag.BreadcrumbExtra = "- All Tasks";
            }

            // showing all the tasks?
            ViewBag.ShowAll = !string.IsNullOrEmpty(all) ? all : "false";
            
            return View(anthRTask);

        }

        // GET: AnthRTasks/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnthRTask anthRTask = await _db.AnthRTask.FindAsync(id);
            if (anthRTask == null)
            {
                return HttpNotFound();
            }
            return View(anthRTask);
        }

        // GET: AnthRTasks/Create
        public ActionResult Create(int? id)
        {

            // get specific project if we have an id
            var projects = _db.Project.Where(p => !id.HasValue || p.Id.Equals(id.Value)).ToList();
            projects.ForEach(p => { p.Name = p.MasterSite.Name + " - " + p.Name; });

            ViewBag.ProjectId = new SelectList(projects, "Id", "Name");
            ViewBag.StatusId = new SelectList(_db.Status, "Id", "Description");
            ViewBag.Priority = new SelectList(Enumerable.Range(1, 4), "Priority");

            return View();

        }

        public ActionResult CreateAjaxForm(int? id)
        {
             // get specific project if we have an id
            var projects = _db.Project.Where(p => !id.HasValue || p.Id.Equals(id.Value)).ToList();
            projects.ForEach(p => { p.Name = p.MasterSite.Name + " - " + p.Name; });

            ViewBag.ProjectId = new SelectList(projects, "Id", "Name");
            ViewBag.StatusId = new SelectList(_db.Status, "Id", "Description");
            ViewBag.Priority = new SelectList(Enumerable.Range(1, 4), "Priority");

            return View();
        }

        // POST: AnthRTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,ProjectId,StatusId,Name,Description,RequestedBy,PlannedStart,Deadline,Priority")] AnthRTask anthRTask)
        {
            if (ModelState.IsValid)
            {

                // add the username
                anthRTask.Username = User.Identity.Name;

                _db.AnthRTask.Add(anthRTask);
                await _db.SaveChangesAsync();
                //return RedirectToAction("Index");

                // redirect to allocate staff to the task
                return RedirectToAction("Create", "StaffOnTasks", new { id = anthRTask.ProjectId, taskId = anthRTask.Id });
                
            }

            ViewBag.ProjectId = new SelectList(_db.Project, "Id", "Name", anthRTask.ProjectId);
            ViewBag.StatusId = new SelectList(_db.Status, "Id", "Description", anthRTask.StatusId);
            ViewBag.Priority = new SelectList(Enumerable.Range(1, 4), "Priority");
            return View(anthRTask);
        }

        // GET: AnthRTasks/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnthRTask anthRTask = await _db.AnthRTask.FindAsync(id);
            if (anthRTask == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.ProjectId = new SelectList(_db.Project, "Id", "Name", anthRTask.ProjectId);
            ViewBag.StatusId = new SelectList(_db.Status, "Id", "Description", anthRTask.StatusId);
            ViewBag.Priority = new SelectList(Enumerable.Range(1, 4), anthRTask.Priority);

            return View(anthRTask);
        }

        // POST: AnthRTasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,ProjectId,StatusId,Name,Description,RequestedBy,PlannedStart,Deadline,Priority,Username")] AnthRTask anthRTask)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(anthRTask).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectId = new SelectList(_db.Project, "Id", "Name", anthRTask.ProjectId);
            ViewBag.StatusId = new SelectList(_db.Status, "Id", "Description", anthRTask.StatusId);
            ViewBag.Priority = new SelectList(Enumerable.Range(1, 4), "Priority");
            return View(anthRTask);
        }

        // GET: AnthRTasks/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnthRTask anthRTask = await _db.AnthRTask.FindAsync(id);
            if (anthRTask == null)
            {
                return HttpNotFound();
            }
            return View(anthRTask);
        }

        // POST: AnthRTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            AnthRTask anthRTask = await _db.AnthRTask.FindAsync(id);
            _db.AnthRTask.Remove(anthRTask);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> CompleteTask(int id)

anthR.Web/Views/Tasks/CompleteAjaxTask.cshtml
@model anthR.Web.Models.arTask.AnthRTask

@{
    Layout = null;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h4>Complete Task</h4>

        <hr />
        <div class="col-sm-12">
            <p>
                Are you sure you want to set the status of the following task to Complete?
                <br /><br />
                @Model.Project.MasterSite.Name - @Model.Project.Name
                <br />
                @Model.Name
                <br />
                @Model.Description
                <br /><br />
            </p>
        </div>
        
        <div class="form-group">
            <div class="col-md-10">
                <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Complete</button>                
                <button type="button" class="btn btn-primary close-modal"><i class="glyphicon glyphicon-remove"></i> Cancel</button>                
            </div>
        </div>

    </div>
}

anthR.Web/Views/Tasks/CompleteTask.cshtml
@model anthR.Web.Models.arTask.AnthRTask

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h4>AnthRTask</h4>

        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control form-control-long", rows = "10" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCompleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.DateCompleted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCompleted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

anthR.Web/Views/Tasks/Delete.cshtml
@model anthR.Web.Models.arTask.AnthRTask

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AnthRTask</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Project.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

anthR.Web/Views/Tasks/Index.cshtml
@model IEnumerable<anthR.Web.Models.arTask.AnthRTask>

@{
    ViewBag.Title = "Index";
    string showAll = ViewBag.ShowAll;
    int? _id = null;
    // get project id if exists.
    if (ViewContext.RouteData.Values["id"] != null && !string.IsNullOrEmpty(ViewContext.RouteData.Values["id"].ToString()))
    {
        _id = int.Parse(ViewContext.RouteData.Values["id"].ToString());
    }
}

@*http://codyhouse.co/demo/contact-form/index.html*@

<div class="row">

    <div class="col-sm-6">
        @Html.RawActionLink("<i class=\"glyphicon glyphicon-plus-sign\"></i> Create New Task", "Create", "Tasks", new { id = _id }, new { @class = "btn btn-xs btn-primary" })
        |
        @if (string.IsNullOrEmpty(Request["completed"]))
        {
            @Html.RawActionLink("Completed Tasks", "Index", "Tasks", new { completed = true, all = showAll }, new { @class = "btn btn-xs btn-primary" })
        }
        else
        {
            @Html.RawActionLink("Live Tasks", "Index", "Tasks", new { all = showAll }, new { @class = "btn btn-xs btn-primary" })
        }                
        <input id="all" name="all" type="checkbox" @(showAll.Equals("true", StringComparison.OrdinalIgnoreCase) ? "checked" : "") /> Show all tasks for project(s)
    </div>
        
    <div class="col-sm-6">
        
        <form class="form-group form-group-sm form-inline">
            <fieldset>
                <div class="row">
                    <div class="col-sm-4 pull-right">
                        <label class="pull-right">
                            Priority
                            <select class="form-control" id="priority">
                                <option value="0">All</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            </select>
                        </label>
                    </div>
                    <div class="col-sm-5 pull-right">
                        <label class="pull-right">
                            Status
                            <select class="form-control" id="status">
                                <option value="0">All</option>
                                <option value="1">Awaiting Start</option>
                                <option value="2">In-Progress</option>
                                <option value="3">Waiting</option>
                                <option value="4">Complete</option>
                                <option value="5">Delegated</option>
                            </select>
                        </label>
                    </div>
                </div>
            </fieldset>
        </form>

    </div>

</div>

<div class="row">

    <div class="col-sm-12 with-padding">

        <table class="table table-hover" id="project-tasks">            
            <tr>
                <th style="width: 4px; padding: 0;"></th>
                <th style="width: 4px; padding: 0;"></th>
                <th>
                    Task
                </th>
                <th>Planned Start</th>
                <th>Deadline</th>
                <th>Staff On Task</th>
                <th class="text-right">Options</th>
            </tr>

            @foreach (var item in Model)
            {

                <tr class="@string.Format("ps p-{0} s-{1}", item.Priority, item.StatusId)">
                    <td style="width: 4px; padding: 0; @string.Format("background-color: {0}", item.Status.HexColor)" title="@item.Status.Description"></td>
                    <td class="@string.Format("priority-{0}", item.Priority)" title="@string.Format("Priority {0}", item.Priority)" style="width: 4px; padding: 0;"></td>
                    <td class="searchable" title="@string.Format("Status: {0} - Priority: {1}", item.Status.Description, item.Priority)">
                        <i>
                            @Html.DisplayFor(modelItem => item.Project.MasterSite.Name)<br />
                            <strong>@Html.DisplayFor(modelItem => item.Project.Name)</strong>
                        </i>
                        <br />
                        <strong>@Html.DisplayFor(modelItem => item.Name)</strong>
                    </td>
                    <td>
                        @(item.PlannedStart.Year > 1900 ? item.PlannedStart.ToString("dd MMM hh:mm tt") : "n/a")
                    </td>
                    <td>
                        @(item.Deadline.Year > 1900 ? item.Deadline.ToString("dd MMM hh:mm tt") : "n/a")
                    </td>
                    <td>
                        @if (item.StaffOnTasks.Any())
                        {
                            foreach (var staff in item.StaffOnTasks)
                            {
                                <span>@Html.ActionLink(staff.Staff.Name, "Details", "Staff", new { id = staff.StaffId }, null)</span>
                            }
                        }
                    </td>

                    <td>
                        <div class="btn-group pull-right">
                            <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                                <span class="glyphicon glyphicon-menu-hamburger"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Add Staff", "Create", "StaffOnTasks", new { id = item.ProjectId, taskId = item.Id }, null)</li>
                                <li>@Html.ActionLink("Allocate Time", "Create", "Timesheets", new { id = item.Id }, null) </li>                                    
                                <li>@Html.RawActionLink(string.Format("Time Allocated{0}", item.Timesheet.Any() ? string.Format(" ({0})", item.Timesheet.Count()) : ""), "TimeAllocated", "Tasks", new { id = item.Id }, null) </li>                                    
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Edit", "Edit", "Tasks", new { id = item.Id }, null)</li>
                                <li>@Html.ActionLink("Details", "Details", "Tasks", new { id = item.Id }, null)</li>
                                <li>@Html.ActionLink("Delete", "Delete", "Tasks", new { id = item.Id }, null)</li>
                                <li>@Html.ActionLink("Complete", "CompleteTask", "Tasks", new { id = item.Id }, new { @class = "task-complete", data_id = item.Id })</li>
                            </ul>
                        </div>                                             
                    </td>
                </tr>
            }

        </table>

    </div>

</div>

@section scripts{

    <script>
        $(function () {

            var $ddlStatus = $('#status');
            var $ddlPriority = $('#priority');
            var $tasks = $('#project-tasks');

            $(document).on('change', '#status, #priority', function () { filterList(); });
            
            var filterList = function () {

                var status = $ddlStatus.val();
                var priority = $ddlPriority.val();

                $('.ps').hide();

                if (priority == "0" && status == "0") {
                    $('.ps').show();
                }
                else if (priority != "0" && status == "0") {
                    $('.p-' + priority).show();
                }
                else if (priority == "0" && status != "0") {
                    $('.s-' + status).show();
                }
                else {
                    $('.p-' + priority + '.s-' + status).show();
                }

            };

            // handle Ctrl + S
            $(document).on('keydown', function (e) { handleShortcuts(e); });
            $(document).on('click', '.close-search, .close-modal', function () {
                closeSearch();
                // kill modals
                $('.modal').remove();
            });
            var handleShortcuts = function (e) {

                // Ctrl + F
                if (e.keyCode === 114 || (e.ctrlKey && e.keyCode === 70)) {
                    e.preventDefault();
                    // pop up custom search
                    $('#searchBox').show();
                    $('#search').focus();
                }

                // escape key
                if (e.keyCode == 27) {
                    // close search
                    closeSearch();
                    // kill modals
                    $('.modal').remove();
                }

                // Ctrl + C
                if (e.ctrlKey && e.keyCode === 67) {
                    // load create form into modal
                    var $modal = $('<div />').addClass('modal').addClass('show');
                    var $modalInner = $('<div />').addClass('modal-inner');
                    $.get('/tasks/createajaxform', null, function (data) {
                        $modalInner.append(data);
                        $('body').append($modal.append($modalInner));
                    });                    
                }                

            };

            $(document).on('keyup', '#search', function () {
                searchList();
            });

            var closeSearch = function () {
                $('#searchBox').hide();
                $('#search').val('');
                searchList();
            };

            var searchList = function () {

                var value = $('#search').val();

                $("table tr").each(function (index) {
                    if (index !== 0) {

                        $row = $(this);

                        var id = $row.find("td.searchable").text();                        
                        if (id.toLowerCase().indexOf(value.toLowerCase()) > -1) {
                            $row.show();
                        }
                        else {
                            $row.hide(); 
                        }

                    }
                });

            };

            // quick complete
            $(document).on('click', '.task-complete', function (e) {

                e.preventDefault();

                // show complete modal
                var $modal = $('<div />').addClass('modal').addClass('show');
                var $modalInner = $('<div />').addClass('modal-inner');
                $.get('/tasks/completeajaxtask', {id: $(this).data('id')}, function (data) {
                    $modalInner.append(data);
                    $('body').append($modal.append($modalInner));
                });

            });

            $(document).on('change', '#all', function () {
                var href = window.location.pathname;
                var query = window.location.search.replace(/([?&]all)=[^?&]+/, '');
                var isChecked = $(this).is(':checked');               
                href = href.replace(/([?&]all)=[^?&]+/, '');
                window.location = href + query + (query === '' ? '?' : '&') + 'all=' + isChecked;
            });

        });
    </script>

}